webtalk_init -webtalk_dir C:/Users/Sam Eadie/Documents/University Work/CSSE4010/pracs/prac3/project3/project3.sim/sim_1/behav/xsim/xsim.dir/test_bcd_1_adder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 30 13:18:45 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a597e50e-4407-4f57-a296-a4f9f533ede2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "440a1b63c1fb42ac9d4a540bde452ff0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5480_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2136938263 -regid "" -xml C:/Users/Sam Eadie/Documents/University Work/CSSE4010/pracs/prac3/project3/project3.sim/sim_1/behav/xsim/xsim.dir/test_bcd_1_adder_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Sam Eadie/Documents/University Work/CSSE4010/pracs/prac3/project3/project3.sim/sim_1/behav/xsim/xsim.dir/test_bcd_1_adder_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Sam Eadie/Documents/University Work/CSSE4010/pracs/prac3/project3/project3.sim/sim_1/behav/xsim/xsim.dir/test_bcd_1_adder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
